SAMPLE_VENDORS = [
    # ── COMMUNICATION & COLLABORATION ────────────────────────────────────────
    {
        "vendor": "Slack",
        "department": "IT Operations",
        "annual_cost": 87000,
        "seat_count": 950,
        "seats_used": 901,
        "contract_type": "Annual",
        "renewal_date": "2025-01-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": True,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "it@company.com",
        "notes": "Enterprise Grid. Primary comms platform.",
    },
    {
        "vendor": "Zoom",
        "department": "IT Operations",
        "annual_cost": 54000,
        "seat_count": 950,
        "seats_used": 870,
        "contract_type": "Annual",
        "renewal_date": "2025-03-22",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "it@company.com",
        "notes": "No SCIM — manual deprovisioning risk.",
    },
    {
        "vendor": "Google Workspace",
        "department": "IT Operations",
        "annual_cost": 133000,
        "seat_count": 950,
        "seats_used": 948,
        "contract_type": "Annual",
        "renewal_date": "2025-06-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": True,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "it@company.com",
        "notes": "Core productivity suite. Business Plus tier.",
    },
    {
        "vendor": "Loom",
        "department": "Product",
        "annual_cost": 14400,
        "seat_count": 200,
        "seats_used": 61,
        "contract_type": "Annual",
        "renewal_date": "2024-12-10",
        "sso_enabled": True,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Low",
        "owner_email": "product@company.com",
        "notes": "30% utilization. Candidate for seat reduction.",
    },
    {
        "vendor": "Miro",
        "department": "Design",
        "annual_cost": 19200,
        "seat_count": 150,
        "seats_used": 94,
        "contract_type": "Annual",
        "renewal_date": "2025-02-28",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Low",
        "owner_email": "design@company.com",
        "notes": "Whiteboarding. Used mainly by Design and Product.",
    },

    # ── IDENTITY & SECURITY ──────────────────────────────────────────────────
    {
        "vendor": "Okta",
        "department": "IT Operations",
        "annual_cost": 112000,
        "seat_count": 950,
        "seats_used": 950,
        "contract_type": "Annual",
        "renewal_date": "2025-08-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": True,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "it@company.com",
        "notes": "IdP. OIG enabled. 300+ app integrations.",
    },
    {
        "vendor": "CrowdStrike Falcon",
        "department": "IT Operations",
        "annual_cost": 76000,
        "seat_count": 950,
        "seats_used": 942,
        "contract_type": "Annual",
        "renewal_date": "2025-07-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "security@company.com",
        "notes": "EDR. Managed by Security team.",
    },
    {
        "vendor": "1Password Business",
        "department": "IT Operations",
        "annual_cost": 28500,
        "seat_count": 950,
        "seats_used": 801,
        "contract_type": "Annual",
        "renewal_date": "2025-04-30",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": True,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "it@company.com",
        "notes": "Password manager. 84% utilization — push adoption campaign.",
    },
    {
        "vendor": "Lumos",
        "department": "IT Operations",
        "annual_cost": 48000,
        "seat_count": 5,
        "seats_used": 4,
        "contract_type": "Annual",
        "renewal_date": "2025-09-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "it@company.com",
        "notes": "Access governance. IT admin-only platform.",
    },
    {
        "vendor": "Proofpoint",
        "department": "IT Operations",
        "annual_cost": 41000,
        "seat_count": 950,
        "seats_used": 950,
        "contract_type": "Annual",
        "renewal_date": "2025-05-15",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "security@company.com",
        "notes": "Email security. No SSO — admin console only, acceptable.",
    },

    # ── DEVICE MANAGEMENT ────────────────────────────────────────────────────
    {
        "vendor": "Microsoft Intune",
        "department": "IT Operations",
        "annual_cost": 34200,
        "seat_count": 380,
        "seats_used": 372,
        "contract_type": "Annual",
        "renewal_date": "2025-11-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "it@company.com",
        "notes": "MDM for Windows fleet (150 devices) + iOS/Android.",
    },
    {
        "vendor": "Jamf Pro",
        "department": "IT Operations",
        "annual_cost": 29000,
        "seat_count": 420,
        "seats_used": 418,
        "contract_type": "Annual",
        "renewal_date": "2025-11-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "it@company.com",
        "notes": "MDM for macOS fleet. 400 devices.",
    },

    # ── ITSM & PROJECT MGMT ──────────────────────────────────────────────────
    {
        "vendor": "Jira (Atlassian Cloud)",
        "department": "IT Operations",
        "annual_cost": 62000,
        "seat_count": 950,
        "seats_used": 720,
        "contract_type": "Annual",
        "renewal_date": "2025-10-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": True,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "it@company.com",
        "notes": "JSM + Jira Software. Atlassian Guard enabled.",
    },
    {
        "vendor": "ServiceNow",
        "department": "Operations",
        "annual_cost": 88000,
        "seat_count": 50,
        "seats_used": 18,
        "contract_type": "Annual",
        "renewal_date": "2024-12-31",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "ops@company.com",
        "notes": "DUPLICATE of Jira for ITSM. 36% utilization. Renewing Dec 31 — evaluate consolidation.",
    },
    {
        "vendor": "Confluence",
        "department": "IT Operations",
        "annual_cost": 24000,
        "seat_count": 950,
        "seats_used": 610,
        "contract_type": "Annual",
        "renewal_date": "2025-10-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": True,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "it@company.com",
        "notes": "Part of Atlassian suite. Co-term with Jira.",
    },
    {
        "vendor": "Notion",
        "department": "Product",
        "annual_cost": 31200,
        "seat_count": 400,
        "seats_used": 289,
        "contract_type": "Annual",
        "renewal_date": "2025-03-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "product@company.com",
        "notes": "DUPLICATE knowledge base alongside Confluence. Evaluate consolidation.",
    },

    # ── HR & PEOPLE ──────────────────────────────────────────────────────────
    {
        "vendor": "Workday HCM",
        "department": "HR",
        "annual_cost": 145000,
        "seat_count": 950,
        "seats_used": 940,
        "contract_type": "Annual",
        "renewal_date": "2026-01-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "hr@company.com",
        "notes": "Core HRIS. No SCIM — Workday → Okta sync is custom API.",
    },
    {
        "vendor": "Lattice",
        "department": "HR",
        "annual_cost": 38000,
        "seat_count": 950,
        "seats_used": 712,
        "contract_type": "Annual",
        "renewal_date": "2025-06-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "hr@company.com",
        "notes": "Performance management. 75% utilization.",
    },
    {
        "vendor": "Greenhouse",
        "department": "HR",
        "annual_cost": 29000,
        "seat_count": 30,
        "seats_used": 28,
        "contract_type": "Annual",
        "renewal_date": "2025-08-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "recruiting@company.com",
        "notes": "ATS. Recruiter and hiring manager seats.",
    },
    {
        "vendor": "Leapsome",
        "department": "HR",
        "annual_cost": 22000,
        "seat_count": 950,
        "seats_used": 201,
        "contract_type": "Annual",
        "renewal_date": "2025-04-01",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": False,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "hr@company.com",
        "notes": "DUPLICATE of Lattice for performance reviews. 21% utilization. No SSO. No SOC2 Type 2. High risk.",
    },

    # ── SALES & CRM ──────────────────────────────────────────────────────────
    {
        "vendor": "Salesforce",
        "department": "Sales",
        "annual_cost": 198000,
        "seat_count": 180,
        "seats_used": 171,
        "contract_type": "Annual",
        "renewal_date": "2025-07-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": True,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "salesops@company.com",
        "notes": "Core CRM. Enterprise license.",
    },
    {
        "vendor": "Outreach",
        "department": "Sales",
        "annual_cost": 44000,
        "seat_count": 80,
        "seats_used": 74,
        "contract_type": "Annual",
        "renewal_date": "2025-05-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "salesops@company.com",
        "notes": "Sales engagement. AE and SDR team.",
    },
    {
        "vendor": "Gong",
        "department": "Sales",
        "annual_cost": 67000,
        "seat_count": 80,
        "seats_used": 66,
        "contract_type": "Annual",
        "renewal_date": "2025-09-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "salesops@company.com",
        "notes": "Revenue intelligence. Call recording — high data sensitivity.",
    },
    {
        "vendor": "Apollo.io",
        "department": "Sales",
        "annual_cost": 18000,
        "seat_count": 25,
        "seats_used": 9,
        "contract_type": "Monthly",
        "renewal_date": "2024-11-30",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": False,
        "soc2_type1": False,
        "data_classification": "Medium",
        "owner_email": "sdr@company.com",
        "notes": "Prospecting tool. 36% utilization. No SSO. No SOC2. Month-to-month — cancel or renegotiate.",
    },

    # ── MARKETING ────────────────────────────────────────────────────────────
    {
        "vendor": "HubSpot Marketing",
        "department": "Marketing",
        "annual_cost": 52000,
        "seat_count": 40,
        "seats_used": 38,
        "contract_type": "Annual",
        "renewal_date": "2025-02-14",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "marketing@company.com",
        "notes": "Marketing Hub + CMS. Renewing Feb 14.",
    },
    {
        "vendor": "Marketo",
        "department": "Marketing",
        "annual_cost": 43000,
        "seat_count": 20,
        "seats_used": 8,
        "contract_type": "Annual",
        "renewal_date": "2025-01-31",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "marketing@company.com",
        "notes": "DUPLICATE email automation alongside HubSpot. 40% utilization. No SSO. Evaluate consolidation.",
    },
    {
        "vendor": "Figma",
        "department": "Design",
        "annual_cost": 24000,
        "seat_count": 60,
        "seats_used": 57,
        "contract_type": "Annual",
        "renewal_date": "2025-04-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Low",
        "owner_email": "design@company.com",
        "notes": "Design tool. Organization plan.",
    },
    {
        "vendor": "Canva Teams",
        "department": "Marketing",
        "annual_cost": 9600,
        "seat_count": 80,
        "seats_used": 31,
        "contract_type": "Annual",
        "renewal_date": "2025-03-15",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Low",
        "owner_email": "marketing@company.com",
        "notes": "39% utilization. No SSO. Overlaps with Figma for some use cases.",
    },

    # ── ENGINEERING & DEVTOOLS ───────────────────────────────────────────────
    {
        "vendor": "GitHub Enterprise",
        "department": "Engineering",
        "annual_cost": 86000,
        "seat_count": 420,
        "seats_used": 415,
        "contract_type": "Annual",
        "renewal_date": "2025-12-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": True,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "eng@company.com",
        "notes": "EMU deployment. 2,300+ repos.",
    },
    {
        "vendor": "Datadog",
        "department": "Engineering",
        "annual_cost": 94000,
        "seat_count": 120,
        "seats_used": 108,
        "contract_type": "Annual",
        "renewal_date": "2025-06-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "eng@company.com",
        "notes": "Observability. Usage-based — monitor for overages.",
    },
    {
        "vendor": "AWS",
        "department": "Engineering",
        "annual_cost": 320000,
        "seat_count": 80,
        "seats_used": 78,
        "contract_type": "Monthly",
        "renewal_date": "2024-11-30",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "infra@company.com",
        "notes": "Primary cloud. IAM federated via Okta.",
    },
    {
        "vendor": "Sentry",
        "department": "Engineering",
        "annual_cost": 21600,
        "seat_count": 80,
        "seats_used": 62,
        "contract_type": "Annual",
        "renewal_date": "2025-08-01",
        "sso_enabled": True,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "eng@company.com",
        "notes": "Error tracking. 78% utilization.",
    },
    {
        "vendor": "PagerDuty",
        "department": "Engineering",
        "annual_cost": 38400,
        "seat_count": 60,
        "seats_used": 44,
        "contract_type": "Annual",
        "renewal_date": "2025-07-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "eng@company.com",
        "notes": "On-call management. 73% utilization.",
    },
    {
        "vendor": "Linear",
        "department": "Engineering",
        "annual_cost": 19200,
        "seat_count": 200,
        "seats_used": 188,
        "contract_type": "Annual",
        "renewal_date": "2025-05-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Low",
        "owner_email": "eng@company.com",
        "notes": "Project tracking for engineering. DUPLICATE of Jira for some teams.",
    },

    # ── FINANCE & LEGAL ──────────────────────────────────────────────────────
    {
        "vendor": "NetSuite",
        "department": "Finance",
        "annual_cost": 78000,
        "seat_count": 40,
        "seats_used": 38,
        "contract_type": "Annual",
        "renewal_date": "2026-02-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "finance@company.com",
        "notes": "ERP. SOX-relevant system.",
    },
    {
        "vendor": "Expensify",
        "department": "Finance",
        "annual_cost": 14400,
        "seat_count": 950,
        "seats_used": 620,
        "contract_type": "Annual",
        "renewal_date": "2025-04-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "finance@company.com",
        "notes": "Expense management. 65% utilization.",
    },
    {
        "vendor": "Carta",
        "department": "Legal",
        "annual_cost": 22000,
        "seat_count": 10,
        "seats_used": 9,
        "contract_type": "Annual",
        "renewal_date": "2025-10-01",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "legal@company.com",
        "notes": "Cap table management. No SSO — Legal/Finance admin only, review annually.",
    },
    {
        "vendor": "DocuSign",
        "department": "Legal",
        "annual_cost": 17500,
        "seat_count": 30,
        "seats_used": 27,
        "contract_type": "Annual",
        "renewal_date": "2025-09-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "legal@company.com",
        "notes": "eSignature. Legal and Sales use.",
    },

    # ── CUSTOMER SUCCESS ─────────────────────────────────────────────────────
    {
        "vendor": "Zendesk",
        "department": "Customer Success",
        "annual_cost": 81000,
        "seat_count": 60,
        "seats_used": 57,
        "contract_type": "Annual",
        "renewal_date": "2025-11-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "cs@company.com",
        "notes": "Customer support platform.",
    },
    {
        "vendor": "Intercom",
        "department": "Customer Success",
        "annual_cost": 49000,
        "seat_count": 40,
        "seats_used": 16,
        "contract_type": "Annual",
        "renewal_date": "2025-01-15",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "cs@company.com",
        "notes": "DUPLICATE of Zendesk for customer messaging. 40% utilization. No SSO. Renewing Jan 15 — cancel or consolidate.",
    },
    {
        "vendor": "Gainsight",
        "department": "Customer Success",
        "annual_cost": 54000,
        "seat_count": 35,
        "seats_used": 31,
        "contract_type": "Annual",
        "renewal_date": "2025-08-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "cs@company.com",
        "notes": "CS platform. Used by CSM team.",
    },

    # ── DATA & ANALYTICS ─────────────────────────────────────────────────────
    {
        "vendor": "Looker",
        "department": "Data",
        "annual_cost": 92000,
        "seat_count": 120,
        "seats_used": 84,
        "contract_type": "Annual",
        "renewal_date": "2025-06-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "data@company.com",
        "notes": "BI platform. GCP Looker. 70% utilization.",
    },
    {
        "vendor": "Snowflake",
        "department": "Data",
        "annual_cost": 180000,
        "seat_count": 40,
        "seats_used": 38,
        "contract_type": "Monthly",
        "renewal_date": "2024-11-30",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "data@company.com",
        "notes": "Data warehouse. Usage-based — large cost driver.",
    },
    {
        "vendor": "dbt Cloud",
        "department": "Data",
        "annual_cost": 24000,
        "seat_count": 20,
        "seats_used": 18,
        "contract_type": "Annual",
        "renewal_date": "2025-07-15",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "data@company.com",
        "notes": "Data transformation. Data engineering team.",
    },

    # ── PRODUCTIVITY & MISC ──────────────────────────────────────────────────
    {
        "vendor": "Box",
        "department": "IT Operations",
        "annual_cost": 38000,
        "seat_count": 300,
        "seats_used": 112,
        "contract_type": "Annual",
        "renewal_date": "2025-02-01",
        "sso_enabled": True,
        "saml_enabled": True,
        "scim_enabled": True,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "it@company.com",
        "notes": "37% utilization. Overlaps with Google Drive. Evaluate consolidation or seat reduction.",
    },
    {
        "vendor": "Dropbox Business",
        "department": "Operations",
        "annual_cost": 16800,
        "seat_count": 100,
        "seats_used": 23,
        "contract_type": "Annual",
        "renewal_date": "2024-12-15",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "ops@company.com",
        "notes": "23% utilization. DUPLICATE of Box + Google Drive. No SSO. Renewing Dec 15 — cancel.",
    },
    {
        "vendor": "Grammarly Business",
        "department": "Marketing",
        "annual_cost": 7200,
        "seat_count": 60,
        "seats_used": 44,
        "contract_type": "Annual",
        "renewal_date": "2025-05-01",
        "sso_enabled": True,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Low",
        "owner_email": "marketing@company.com",
        "notes": "Writing assistant. 73% utilization.",
    },
    {
        "vendor": "Calendly Teams",
        "department": "Sales",
        "annual_cost": 11400,
        "seat_count": 95,
        "seats_used": 71,
        "contract_type": "Annual",
        "renewal_date": "2025-03-01",
        "sso_enabled": True,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Low",
        "owner_email": "sales@company.com",
        "notes": "Scheduling. 75% utilization.",
    },
    {
        "vendor": "Airtable",
        "department": "Operations",
        "annual_cost": 22800,
        "seat_count": 120,
        "seats_used": 41,
        "contract_type": "Annual",
        "renewal_date": "2025-04-01",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "ops@company.com",
        "notes": "34% utilization. No SSO. Shadow IT origin — evaluate formal adoption or cancel.",
    },
    {
        "vendor": "Zapier",
        "department": "Operations",
        "annual_cost": 13200,
        "seat_count": 15,
        "seats_used": 11,
        "contract_type": "Annual",
        "renewal_date": "2025-06-15",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Medium",
        "owner_email": "ops@company.com",
        "notes": "Automation. No SSO — credentials potentially shared. Audit access.",
    },
    {
        "vendor": "Asana",
        "department": "Marketing",
        "annual_cost": 26400,
        "seat_count": 150,
        "seats_used": 48,
        "contract_type": "Annual",
        "renewal_date": "2024-12-01",
        "sso_enabled": True,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "Low",
        "owner_email": "marketing@company.com",
        "notes": "32% utilization. DUPLICATE of Linear/Jira for project tracking. Renewing Dec 1.",
    },
    {
        "vendor": "Typeform",
        "department": "Marketing",
        "annual_cost": 4800,
        "seat_count": 10,
        "seats_used": 6,
        "contract_type": "Monthly",
        "renewal_date": "2024-11-30",
        "sso_enabled": False,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": False,
        "soc2_type2": False,
        "soc2_type1": False,
        "data_classification": "Low",
        "owner_email": "marketing@company.com",
        "notes": "Survey tool. No SSO. No SOC2. Month-to-month. Evaluate vs Google Forms.",
    },
    {
        "vendor": "Brex",
        "department": "Finance",
        "annual_cost": 0,
        "seat_count": 200,
        "seats_used": 198,
        "contract_type": "Monthly",
        "renewal_date": "2024-11-30",
        "sso_enabled": True,
        "saml_enabled": False,
        "scim_enabled": False,
        "mfa_enforced": True,
        "soc2_type2": True,
        "soc2_type1": True,
        "data_classification": "High",
        "owner_email": "finance@company.com",
        "notes": "Corporate cards + expense. Free platform tier. High data sensitivity.",
    },
]
